def get_tools():
    """Define all available tools/intents for the AI agent"""
    return [
        {
            "type": "function",
            "function": {
                "name": "get_contacts",
                "description": "Fetch all contact data from the CRM.",
                "parameters": {
                    "type": "object",
                    "properties": {},  # No parameters needed
                },
                "required": [],
            },
        },
        {
            "type":"function",
            "function":{
                "name":"create_contact",
                "description":"create contact and extract the payload from user query",
                "parameters":{
                    "type":"object",
                    "properties":{
                        "email":{
                            "type":"string",
                            "description":"The email of contact it should be given by user not generated by LLM , if not provided by user then tell user to give email of contact you want to add"
                        },
                        "first_name":{
                            "type":"string",
                            "description":"the name of the contact"
                        },
                        "last_name":{
                            "type":"string",
                            "description":"the last name of the contact"
                        },
                        "phone":{
                            "type":"string",
                            "description":"the phone number of contact"
                        },
                        "company":{
                            "type":"string",
                            "description":"the company name of a contact"
                        }
                    }
                }

            }
        }
    ]
