TOKEN_FILE = r"token.json"
# SCOPES = (
#     "crm.dealsplits.read_write crm.export crm.import "
#     "crm.lists.read crm.lists.write "
#     "crm.objects.appointments.read crm.objects.appointments.write "
#     "crm.objects.carts.read crm.objects.carts.write "
#     "crm.objects.commercepayments.read crm.objects.commercepayments.write "
#     "crm.objects.companies.read crm.objects.companies.write "
#     "crm.objects.contacts.read crm.objects.contacts.write "
#     "crm.objects.courses.read crm.objects.courses.write "
#     "crm.objects.custom.read crm.objects.custom.write "
#     "crm.objects.deals.read crm.objects.deals.write "
#     "crm.objects.feedback_submissions.read "
#     "crm.objects.goals.read crm.objects.goals.write "
#     "crm.objects.invoices.read crm.objects.invoices.write "
#     "crm.objects.leads.read crm.objects.leads.write "
#     "crm.objects.line_items.read crm.objects.line_items.write "
#     "crm.objects.listings.read crm.objects.listings.write "
#     "crm.objects.marketing_events.read crm.objects.marketing_events.write "
#     "crm.objects.orders.read crm.objects.orders.write "
#     "crm.objects.owners.read "
#     "crm.objects.partner-clients.read crm.objects.partner-clients.write "
#     "crm.objects.partner-services.read crm.objects.partner-services.write "
#     "crm.objects.products.read crm.objects.products.write "
#     "crm.objects.quotes.read crm.objects.quotes.write "
#     "crm.objects.services.read crm.objects.services.write "
#     "crm.objects.subscriptions.read crm.objects.subscriptions.write "
#     "crm.objects.users.read crm.objects.users.write "
#     "crm.pipelines.orders.read crm.pipelines.orders.write "
#     "crm.schemas.appointments.read crm.schemas.appointments.write "
#     "crm.schemas.carts.read crm.schemas.carts.write "
#     "crm.schemas.commercepayments.read crm.schemas.commercepayments.write "
#     "crm.schemas.companies.read crm.schemas.companies.write "
#     "crm.schemas.contacts.read crm.schemas.contacts.write "
#     "crm.schemas.courses.read crm.schemas.courses.write "
#     "crm.schemas.custom.read crm.schemas.deals.read crm.schemas.deals.write "
#     "crm.schemas.invoices.read crm.schemas.invoices.write "
#     "crm.schemas.line_items.read "
#     "crm.schemas.listings.read crm.schemas.listings.write "
#     "crm.schemas.orders.read crm.schemas.orders.write "
#     "crm.schemas.quotes.read "
#     "crm.schemas.services.read crm.schemas.services.write "
#     "crm.schemas.subscriptions.read crm.schemas.subscriptions.write"
# )
SCOPES = (
    "crm.objects.contacts.read crm.objects.contacts.write "
    "crm.objects.companies.read crm.objects.companies.write "
    "crm.objects.deals.read crm.objects.deals.write "
    "crm.lists.read crm.lists.write "
    "crm.schemas.contacts.read crm.schemas.contacts.write "
    "crm.schemas.companies.read crm.schemas.companies.write "
    "crm.schemas.deals.read crm.schemas.deals.write "
    "crm.export crm.import"
)